# PostgreSQL. Versions 9.3 and up are supported.


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: notesapp
  password: NotesApp23

# Development database
development:
  <<: *default
  database: NotesApp_development

# Test database
test:
  <<: *default
  database: NotesApp_test

# Production database credentials
production:
  <<: *default
  database: NotesApp
  username: NotesApp
  password: <%= ENV["NOTESAPP_DATABASE_PASSWORD"] %>
