# PostgreSQL. Versions 9.3 and up are supported.


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

# Development database
development:
  <<: *default
  database: NotesApp_development

# Test database
test:
  <<: *default
  database: NotesApp_test

# Production database credentials
production:
  <<: *default
  database: NotesApp
  url: <%= ENV['DATABASE_URL'] %>
